version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
     - "18888:18888"
    command: stack exec real-world-http
    volumes:
      - .:/app
      - stack-data:/root/.stack
volumes:
  stack-data:
